// Bundles the browser widget (client/widget.ts) into a single self-contained
// HTML string and writes it to src/ui/widget-html.ts for the Worker to serve as
// a ui:// resource. No runtime CDN dependency (see docs/adr/0002).
import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

// zod v4 (pulled in by @modelcontextprotocol/ext-apps) bundles ~40 locale files
// of error messages we never surface (~190 KB). Alias every non-English locale
// to en so zod still has a valid locale but the dead weight drops. KEEP THIS.
const enLocale = path.resolve("node_modules/zod/v4/locales/en.js");
const oneZodLocale = {
  name: "zod-one-locale",
  setup(b) {
    // zod/v4/locales/index.js does `export { default as ar } from "./ar.js"` for
    // every language; redirect each relative locale specifier (except en) to en.
    b.onResolve({ filter: /^\.\/[A-Za-z]{2}([-_][A-Za-z]+)?\.js$/ }, (args) => {
      if (!args.importer.replace(/\\/g, "/").includes("zod/v4/locales")) return;
      if (args.path === "./en.js") return;
      return { path: enLocale };
    });
  },
};

const out = await build({
  entryPoints: ["client/widget.ts"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "none",
  plugins: [oneZodLocale],
});
// Guard against an accidental </script> inside the bundle closing the inline tag.
const js = out.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");

const css = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, system-ui, sans-serif; margin: 0; padding: 14px; color: #111; background: #fff; }
  .card { max-width: 520px; margin: 0 auto; }
  h1 { font-size: 20px; margin: 0 0 12px; }
  .section { margin-bottom: 12px; }
  .label { font-size: 11px; letter-spacing: .04em; text-transform: uppercase; color: #888; margin-bottom: 4px; }
  .muted { color: #999; font-size: 13px; }
  .row { display: flex; gap: 12px; font-size: 14px; padding: 5px 0; border-bottom: 1px solid #f0f0f0; }
  .row-date { color: #666; white-space: nowrap; }
  .row-text { flex: 1; }
  .adder { display: flex; gap: 8px; margin-top: 12px; }
  .adder input { flex: 1; font-size: 16px; padding: 10px; border: 1px solid #ccc; border-radius: 8px; }
  .adder button { font-size: 16px; font-weight: 600; padding: 11px 16px; border: 0; border-radius: 8px; background: #1a6fd4; color: #fff; }
  .adder button:active { background: #155fb0; }
  .status { margin-top: 10px; font-size: 13px; color: #666; min-height: 18px; }
`;

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>__PROJECT_NAME__</title>
<style>${css}</style>
</head>
<body>
  <div class="card">
    <h1>Items</h1>
    <div class="section"><div class="label">Recent</div><div id="items"></div></div>
    <div class="adder">
      <input id="text" type="text" placeholder="Add an item..." />
      <button id="addbtn">Add</button>
    </div>
    <div id="status" class="status">loading...</div>
  </div>
  <script>__BUNDLE__</script>
</body>
</html>`.replace("__BUNDLE__", () => js);

const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
await mkdir("src/ui", { recursive: true });
await writeFile(
  "src/ui/widget-html.ts",
  `// GENERATED by scripts/build-ui.mjs -- do not edit by hand.\nexport const WIDGET_HTML = \`${escaped}\`;\n`
);
console.log(`wrote src/ui/widget-html.ts (html ${html.length} chars, bundle ${js.length} chars)`);
