// Bundles the React widget (client/widget.tsx) + its Tailwind CSS into a single
// self-contained HTML string and writes it to src/ui/widget-html.ts for the
// Worker to serve as a ui:// resource. No runtime CDN dependency (docs/adr/0002).
import { build } from "esbuild";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";
import { mkdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";

// zod v4 (via @modelcontextprotocol/ext-apps) bundles ~40 locale files of error
// messages we never surface (~190 KB). Alias every non-English locale to en so
// zod still has a valid locale but the dead weight drops. KEEP THIS.
const enLocale = path.resolve("node_modules/zod/v4/locales/en.js");
const oneZodLocale = {
  name: "zod-one-locale",
  setup(b) {
    b.onResolve({ filter: /^\.\/[A-Za-z]{2}([-_][A-Za-z]+)?\.js$/ }, (args) => {
      if (!args.importer.replace(/\\/g, "/").includes("zod/v4/locales")) return;
      if (args.path === "./en.js") return;
      return { path: enLocale };
    });
  },
};

// 1. Bundle the React widget (production build; automatic JSX runtime).
const out = await build({
  entryPoints: ["client/widget.tsx"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  jsx: "automatic",
  minify: true,
  write: false,
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [oneZodLocale],
});
// Guard against an accidental </script> inside the bundle closing the inline tag.
const js = out.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");

// 2. Generate the Tailwind CSS (only the utilities the widget actually uses).
const inputCss = await readFile("client/app.css", "utf8");
const { css } = await postcss([tailwindcss()]).process(inputCss, { from: "client/app.css" });

// 3. Assemble one self-contained HTML document (style + script inlined).
const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>__PROJECT_NAME__</title>
<style>__CSS__</style>
</head>
<body>
  <div id="root"></div>
  <script>__BUNDLE__</script>
</body>
</html>`
  .replace("__CSS__", () => css)
  .replace("__BUNDLE__", () => js);

const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
await mkdir("src/ui", { recursive: true });
await writeFile(
  "src/ui/widget-html.ts",
  `// GENERATED by scripts/build-ui.mjs -- do not edit by hand.\nexport const WIDGET_HTML = \`${escaped}\`;\n`
);
console.log(`wrote src/ui/widget-html.ts (html ${html.length}, js ${js.length}, css ${css.length} chars)`);
