import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { WIDGET_HTML } from "./ui/widget-html";

interface Env {
  MCP_OBJECT: DurableObjectNamespace<__CLASS_NAME__>;
  STORE: KVNamespace;
  // Shared secret embedded in the connector URL path (/<MCP_SECRET>/mcp).
  MCP_SECRET?: string;
}

// One KV-backed store: a flat, id-addressable list of Items. Replace `Item`
// and these tools with your real domain -- keep the surface thin (see docs/adr).
const ITEMS_KEY = "items";

type Item = { id: string; at: string; text: string };

const newId = () => crypto.randomUUID().slice(0, 8);

async function readJSON<T>(kv: KVNamespace, key: string, fallback: T): Promise<T> {
  const raw = await kv.get(key);
  return raw ? (JSON.parse(raw) as T) : fallback;
}
async function writeJSON(kv: KVNamespace, key: string, value: unknown): Promise<void> {
  await kv.put(key, JSON.stringify(value));
}

const text = (s: string) => ({ content: [{ type: "text" as const, text: s }] });
const json = (v: unknown) => text(JSON.stringify(v, null, 2));

export class __CLASS_NAME__ extends McpAgent<Env> {
  server = new McpServer({ name: "__PROJECT_NAME__", version: "0.1.0" });

  async init() {
    const kv = () => this.env.STORE;

    // ---- Thin CRUD surface (keep intelligence in Claude, not in tools) -----
    this.server.registerTool(
      "list_items",
      {
        title: "List items",
        description:
          "Recall stored Items, most recent first. Optionally filter by text " +
          "(substring) and cap with limit (default 50).",
        inputSchema: {
          query: z.string().optional().describe("Filter by text (substring match)"),
          limit: z.number().int().positive().optional().describe("Max items (default 50)"),
        },
      },
      async ({ query, limit }) => {
        let items = await readJSON<Item[]>(kv(), ITEMS_KEY, []);
        if (query) {
          const q = query.toLowerCase();
          items = items.filter((i) => i.text.toLowerCase().includes(q));
        }
        items = items.sort((a, b) => b.at.localeCompare(a.at)).slice(0, limit ?? 50);
        return json(items);
      }
    );

    this.server.registerTool(
      "save_item",
      {
        title: "Save or correct an item",
        description:
          "Append a new Item, or upsert one by id. Pass text. Pass id (from a prior " +
          "call) to overwrite that Item -- use to correct a mistake. Returns the saved " +
          "Item as JSON so its id is machine-readable.",
        inputSchema: {
          text: z.string().describe("The item's text"),
          id: z.string().optional().describe("Existing Item id to overwrite (upsert)"),
        },
      },
      async ({ text: itemText, id }) => {
        const items = await readJSON<Item[]>(kv(), ITEMS_KEY, []);
        let item: Item;
        if (id) {
          const idx = items.findIndex((i) => i.id === id);
          item = { id, at: idx >= 0 ? items[idx].at : new Date().toISOString(), text: itemText };
          if (idx >= 0) items[idx] = item;
          else items.push(item);
        } else {
          item = { id: newId(), at: new Date().toISOString(), text: itemText };
          items.push(item);
        }
        await writeJSON(kv(), ITEMS_KEY, items);
        return json(item);
      }
    );

    this.server.registerTool(
      "delete_item",
      {
        title: "Delete an item",
        description: "Permanently remove an Item by id.",
        inputSchema: { id: z.string().describe("Item id to delete") },
      },
      async ({ id }) => {
        const items = await readJSON<Item[]>(kv(), ITEMS_KEY, []);
        const next = items.filter((i) => i.id !== id);
        await writeJSON(kv(), ITEMS_KEY, next);
        return text(
          next.length === items.length ? `No item with id ${id}.` : `Deleted item ${id}.`
        );
      }
    );

    // ---- View (interactive MCP Apps widget) -------------------------------
    // One dispatcher renders in-flow capture/recall widgets; the widget reads
    // and writes through the CRUD tools above via callServerTool. The HTML
    // bundle is generated by scripts/build-ui.mjs. See docs/adr/0002.
    const VIEW_RESOURCE_URI = "ui://views/app.html";
    const VIEW_MIME = "text/html;profile=mcp-app";
    this.server.registerResource(
      "views",
      VIEW_RESOURCE_URI,
      { mimeType: VIEW_MIME },
      async () => ({
        contents: [{ uri: VIEW_RESOURCE_URI, mimeType: VIEW_MIME, text: WIDGET_HTML }],
      })
    );

    this.server.registerTool(
      "open_view",
      {
        title: "Open a view",
        description:
          "Render an interactive in-chat widget (a View). view='items' shows recent " +
          "Items and lets the user add one hands-on, without typing into chat. Use when " +
          "the user wants to browse or capture Items interactively.",
        inputSchema: {
          view: z.enum(["items"]).describe("Which view to open"),
        },
        _meta: { ui: { resourceUri: VIEW_RESOURCE_URI, visibility: ["model", "app"] } },
      },
      async ({ view }) => {
        const items = (await readJSON<Item[]>(kv(), ITEMS_KEY, []))
          .sort((a, b) => b.at.localeCompare(a.at))
          .slice(0, 10);
        return json({ view, items });
      }
    );
  }
}

const mcpHandler = __CLASS_NAME__.serve("/mcp");

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // Auth = an unguessable secret in the URL path: /<MCP_SECRET>/mcp. See docs/adr/0001.
    const url = new URL(request.url);
    const parts = url.pathname.split("/").filter(Boolean);
    if (env.MCP_SECRET && parts.length === 2 && parts[0] === env.MCP_SECRET && parts[1] === "mcp") {
      url.pathname = "/mcp";
      return mcpHandler.fetch(new Request(url, request), env, ctx);
    }
    return new Response("Not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;
